# Generated by Django 5.2.7 on 2025-10-16 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('project_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('possession_date', models.CharField(blank=True, max_length=50)),
                ('project_summary', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=255)),
                ('full_address', models.TextField(blank=True)),
                ('landmark', models.CharField(blank=True, max_length=255)),
                ('pincode', models.CharField(blank=True, max_length=10)),
                ('bhk_type', models.CharField(max_length=50)),
                ('property_category', models.CharField(max_length=100)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('carpet_area', models.FloatField(blank=True, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('balcony', models.IntegerField(blank=True, null=True)),
                ('furnished_type', models.CharField(blank=True, max_length=50)),
                ('property_images', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'property_listings',
            },
        ),
    ]
